name: crack-kan
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.5
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pillow=10.3.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.9.19
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.3.0
  - torchtriton=2.3.0
  - torchvision=0.18.0
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - click==8.1.7
      - clip==1.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastapi==0.112.2
      - fastsam==0.1.1
      - ffmpy==0.4.0
      - filelock==3.15.4
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - ftfy==6.2.3
      - gradio==3.35.2
      - gradio-client==1.3.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - imageio==2.34.2
      - ipython==8.18.1
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - multidict==6.0.5
      - narwhals==1.6.0
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.7
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pykan==0.0.5
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.35.1
      - regex==2024.7.24
      - rpds-py==0.20.0
      - scikit-learn==1.1.3
      - scipy==1.13.1
      - seaborn==0.13.2
      - segment-anything==1.0
      - semantic-version==2.10.0
      - six==1.16.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.38.2
      - sympy==1.11.1
      - threadpoolctl==3.5.0
      - tifffile==2024.6.18
      - torch==2.2.2
      - tqdm==4.66.2
      - traitlets==5.14.3
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uc-micro-py==1.0.3
      - ultralytics==8.2.84
      - ultralytics-thop==2.0.5
      - uvicorn==0.30.6
      - wcwidth==0.2.13
      - websockets==12.0
      - yarl==1.9.6
